const lectureDetails={"lecture-1":{title:"Введение в Unreal Engine 5",text:"Разбираем установку, структуру проекта, Content Browser, Viewport, основные панели и навигацию в 3D-сцене."},"lecture-2":{title:"Blueprint System",text:"Учимся создавать визуальную логику: события, переменные, ветвления, функции и простые игровые реакции."},"lecture-3":{title:"Создание персонажа",text:"Настраиваем Character Controller, камеру, ввод, базовые анимации и поведение игрового персонажа."},"lecture-4":{title:"Физика и взаимодействия",text:"Работаем с collision presets, физическими объектами, overlap-событиями и trigger zones."},"lecture-5":{title:"Создание игрового уровня",text:"Собираем уровень с landscape, освещением, окружением, композиционными акцентами и атмосферой."},"lecture-6":{title:"UI и оптимизация",text:"Создаем HUD и widgets, затем улучшаем FPS через настройку ассетов, освещения и визуальных эффектов."}};
const loader=document.querySelector(".loader"),nav=document.querySelector(".nav"),navToggle=document.querySelector(".nav-toggle"),progress=document.querySelector(".scroll-progress"),toTop=document.querySelector(".to-top"),modal=document.querySelector(".modal"),modalTitle=document.querySelector(".modal__title"),modalText=document.querySelector(".modal__text"),modalClose=document.querySelector(".modal__close"),cursorDot=document.querySelector(".cursor-dot"),cursorRing=document.querySelector(".cursor-ring"),canvas=document.querySelector(".particle-canvas"),ctx=canvas.getContext("2d");
let particles=[],mouseX=window.innerWidth/2,mouseY=window.innerHeight/2;
window.addEventListener("load",()=>{setTimeout(()=>loader.classList.add("is-hidden"),450)});
navToggle.addEventListener("click",()=>{const isOpen=nav.classList.toggle("is-open");navToggle.setAttribute("aria-expanded",String(isOpen))});
document.querySelectorAll(".nav a").forEach(link=>{link.addEventListener("click",()=>{nav.classList.remove("is-open");navToggle.setAttribute("aria-expanded","false")})});
function updateScrollUi(){const maxScroll=document.documentElement.scrollHeight-window.innerHeight;const percent=maxScroll>0?window.scrollY/maxScroll*100:0;progress.style.width=`${percent}%`;toTop.classList.toggle("is-visible",window.scrollY>650)}
window.addEventListener("scroll",updateScrollUi,{passive:true});toTop.addEventListener("click",()=>window.scrollTo({top:0,behavior:"smooth"}));updateScrollUi();
const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");revealObserver.unobserve(entry.target)}})},{threshold:.14});
document.querySelectorAll(".reveal").forEach(element=>revealObserver.observe(element));
document.querySelectorAll("[data-modal]").forEach(button=>{button.addEventListener("click",()=>{const details=lectureDetails[button.dataset.modal];modalTitle.textContent=details.title;modalText.textContent=details.text;modal.classList.add("is-open");modal.setAttribute("aria-hidden","false")})});
function closeModal(){modal.classList.remove("is-open");modal.setAttribute("aria-hidden","true")}
modalClose.addEventListener("click",closeModal);modal.addEventListener("click",event=>{if(event.target===modal)closeModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape")closeModal()});
document.querySelector(".contact-form").addEventListener("submit",event=>{event.preventDefault();const button=event.currentTarget.querySelector("button");const originalText=button.textContent;button.textContent="Заявка отправлена";setTimeout(()=>{button.textContent=originalText;event.currentTarget.reset()},1800)});
document.addEventListener("mousemove",event=>{mouseX=event.clientX;mouseY=event.clientY;cursorDot.style.left=`${mouseX}px`;cursorDot.style.top=`${mouseY}px`});
function animateCursorRing(){const currentLeft=parseFloat(cursorRing.style.left||mouseX),currentTop=parseFloat(cursorRing.style.top||mouseY);cursorRing.style.left=`${currentLeft+(mouseX-currentLeft)*.18}px`;cursorRing.style.top=`${currentTop+(mouseY-currentTop)*.18}px`;requestAnimationFrame(animateCursorRing)}animateCursorRing();
document.querySelectorAll("a,button,input,summary").forEach(item=>{item.addEventListener("mouseenter",()=>cursorRing.classList.add("is-hover"));item.addEventListener("mouseleave",()=>cursorRing.classList.remove("is-hover"))});
document.addEventListener("mousemove",event=>{document.querySelectorAll(".parallax-card").forEach(card=>{const depth=Number(card.dataset.depth||.04),x=(event.clientX-window.innerWidth/2)*depth,y=(event.clientY-window.innerHeight/2)*depth;card.style.transform=`translate3d(${x}px,${y}px,0)`})});
function resizeCanvas(){const rect=canvas.getBoundingClientRect(),density=Math.min(window.devicePixelRatio||1,2);canvas.width=rect.width*density;canvas.height=rect.height*density;ctx.setTransform(density,0,0,density,0,0);particles=Array.from({length:Math.min(90,Math.floor(rect.width/14))},()=>({x:Math.random()*rect.width,y:Math.random()*rect.height,vx:(Math.random()-.5)*.45,vy:(Math.random()-.5)*.45,size:Math.random()*2+.8}))}
function drawParticles(){const rect=canvas.getBoundingClientRect();ctx.clearRect(0,0,rect.width,rect.height);particles.forEach((particle,index)=>{particle.x+=particle.vx;particle.y+=particle.vy;if(particle.x<0||particle.x>rect.width)particle.vx*=-1;if(particle.y<0||particle.y>rect.height)particle.vy*=-1;ctx.beginPath();ctx.arc(particle.x,particle.y,particle.size,0,Math.PI*2);ctx.fillStyle="rgba(0,229,255,.72)";ctx.fill();for(let next=index+1;next<particles.length;next+=1){const other=particles[next],distance=Math.hypot(particle.x-other.x,particle.y-other.y);if(distance<110){ctx.beginPath();ctx.moveTo(particle.x,particle.y);ctx.lineTo(other.x,other.y);ctx.strokeStyle=`rgba(139,92,246,${1-distance/110})`;ctx.lineWidth=.45;ctx.stroke()}}});requestAnimationFrame(drawParticles)}
resizeCanvas();drawParticles();window.addEventListener("resize",resizeCanvas);
